language: node_js
node_js:
- '4.2'

env:
  global:
  - GH_REF=github.com/sdgandhi/prose.git
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: hxRGUVrXTnNbjl+r4nVgltJO0Lf0odyRb/e7EVnw3vWgHkPQv7mpbBXvDLWpQJSf+IQDFCXbo7uG4gip3bJ0yftGrU1llmpCaOFmqGOH3q/iLpBXh2o27psF8jojWBvpfrvlZWHTH6SMfy2wF/LYUDrA5Nd6t2ofdcHmxK+FknzPdWFGBKrGyozhrKfeNeOPhExie1Sj8kJbKpdDpq9kgQKzyufUfoie0pHKWmq8jMT3HDJzJtUYAMVWVOdVD9NF+J7KO36ebw3kzYax4bDVmpKemhuQtGmJKo0Zi9YucqjjdQTEGV2BptH2ZUVZo46k4H2B0wykaqio2XxxJiLBLJMJEaNYhl/cnR8ErsPbZwkrWt+i9KU9aYinGESpINd8/CklDes0VmBZseBLVmVZTD/OP+PzvxLsFkQjVSjMyDSGbSziTWPk3sUBBPzvw2nZDkUx45B9A2GGRPTGGUh2vso+ARRc+dYaDt0IRI3vO784V/ufzVAwFpZHAc1LBShMQyXVgMY4h0cmG8TZcN1qTlOzKKVHxd79f6dDqyzEsQphRvywS2Ze9/Vb+SQ7raD9yK7N8gahipUVplceKP46x3jNxe+JPGQXGDQE/CxDR71794jQaDWRbFUJ+/+jhL1IMdQjynBl4O994DirU8Z9hIvIyT2oWvIqrQcxZe2ohI4=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh

before_script:
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
